services:
  server:
    container_name: server
    build: ./server
    ports:
      - 0.0.0.0:8080:8080

  client:
    container_name: client
    build: ./client
    depends_on:
      - server
    ports:
      - 0.0.0.0:4200:80
