services:
  server:
    container_name: server
    build: ./server
    depends_on:
      - database
    ports:
      - 8080:8080
    develop:
      watch:
        - action: rebuild
          path: ./server
          target: /app

  client:
    container_name: client
    build: ./client
    depends_on:
      - server
    ports:
      - 4200:80
    develop:
      watch:
        - action: rebuild
          path: ./client
          target: /usr/src/app

  database:
    container_name: mongo
    build: ./database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./database/data:/data/db
      - ./database/logs:/var/log/mongodb/
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
